//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.11 at 01:24:08 PM CEST 
//


package de.factfinder.xml610.search;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}activeQuestions" minOccurs="0"/>
 *         &lt;element ref="{}advisorTree" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "activeQuestions",
    "advisorTree"
})
@XmlRootElement(name = "advisor")
public class Advisor {

    protected ActiveQuestions activeQuestions;
    protected AdvisorTree advisorTree;

    /**
     * Gets the value of the activeQuestions property.
     * 
     * @return
     *     possible object is
     *     {@link ActiveQuestions }
     *     
     */
    public ActiveQuestions getActiveQuestions() {
        return activeQuestions;
    }

    /**
     * Sets the value of the activeQuestions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActiveQuestions }
     *     
     */
    public void setActiveQuestions(ActiveQuestions value) {
        this.activeQuestions = value;
    }

    /**
     * Gets the value of the advisorTree property.
     * 
     * @return
     *     possible object is
     *     {@link AdvisorTree }
     *     
     */
    public AdvisorTree getAdvisorTree() {
        return advisorTree;
    }

    /**
     * Sets the value of the advisorTree property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdvisorTree }
     *     
     */
    public void setAdvisorTree(AdvisorTree value) {
        this.advisorTree = value;
    }

}
