//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.11 at 01:24:08 PM CEST 
//


package de.factfinder.xml610.search;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}searchParams"/>
 *       &lt;/sequence>
 *       &lt;attribute name="field" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="count" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="clusterLevel" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="selected" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}boolean">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="previewImage">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="selectedMin" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="selectedMax" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="absoluteMin" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="absoluteMax" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "searchParams"
})
@XmlRootElement(name = "element")
public class Element {

    @XmlElement(required = true)
    protected String searchParams;
    @XmlAttribute(name = "field")
    protected String field;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "count", required = true)
    protected int count;
    @XmlAttribute(name = "clusterLevel", required = true)
    protected int clusterLevel;
    @XmlAttribute(name = "selected", required = true)
    protected boolean selected;
    @XmlAttribute(name = "previewImage")
    protected String previewImage;
    @XmlAttribute(name = "selectedMin")
    protected BigInteger selectedMin;
    @XmlAttribute(name = "selectedMax")
    protected BigInteger selectedMax;
    @XmlAttribute(name = "absoluteMin")
    protected BigInteger absoluteMin;
    @XmlAttribute(name = "absoluteMax")
    protected BigInteger absoluteMax;

    /**
     * Gets the value of the searchParams property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchParams() {
        return searchParams;
    }

    /**
     * Sets the value of the searchParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchParams(String value) {
        this.searchParams = value;
    }

    /**
     * Gets the value of the field property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField() {
        return field;
    }

    /**
     * Sets the value of the field property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField(String value) {
        this.field = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the count property.
     * 
     */
    public int getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     */
    public void setCount(int value) {
        this.count = value;
    }

    /**
     * Gets the value of the clusterLevel property.
     * 
     */
    public int getClusterLevel() {
        return clusterLevel;
    }

    /**
     * Sets the value of the clusterLevel property.
     * 
     */
    public void setClusterLevel(int value) {
        this.clusterLevel = value;
    }

    /**
     * Gets the value of the selected property.
     * 
     */
    public boolean isSelected() {
        return selected;
    }

    /**
     * Sets the value of the selected property.
     * 
     */
    public void setSelected(boolean value) {
        this.selected = value;
    }

    /**
     * Gets the value of the previewImage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreviewImage() {
        return previewImage;
    }

    /**
     * Sets the value of the previewImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreviewImage(String value) {
        this.previewImage = value;
    }

    /**
     * Gets the value of the selectedMin property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSelectedMin() {
        return selectedMin;
    }

    /**
     * Sets the value of the selectedMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSelectedMin(BigInteger value) {
        this.selectedMin = value;
    }

    /**
     * Gets the value of the selectedMax property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSelectedMax() {
        return selectedMax;
    }

    /**
     * Sets the value of the selectedMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSelectedMax(BigInteger value) {
        this.selectedMax = value;
    }

    /**
     * Gets the value of the absoluteMin property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAbsoluteMin() {
        return absoluteMin;
    }

    /**
     * Sets the value of the absoluteMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAbsoluteMin(BigInteger value) {
        this.absoluteMin = value;
    }

    /**
     * Gets the value of the absoluteMax property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAbsoluteMax() {
        return absoluteMax;
    }

    /**
     * Sets the value of the absoluteMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAbsoluteMax(BigInteger value) {
        this.absoluteMax = value;
    }

}
