//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.11 at 01:24:08 PM CEST 
//


package de.factfinder.xml610.search;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element ref="{}searchStatus"/>
 *           &lt;element ref="{}articleNumberSearchStatus" minOccurs="0"/>
 *           &lt;element ref="{}searchTimedOut" minOccurs="0"/>
 *           &lt;element name="productsPerPageOptions">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="option" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element ref="{}searchParams"/>
 *                             &lt;/sequence>
 *                             &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                   &lt;attribute name="default" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                   &lt;attribute name="selected" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="searchControlParams">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="disableCache" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                     &lt;element name="generateAdvisorTree" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                     &lt;element name="idsOnly" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                     &lt;element name="useAsn" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                     &lt;element name="useCampaigns" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                     &lt;element name="useFoundWords" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                     &lt;element name="useKeywords" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="searchParams">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element ref="{}searchPhrase" minOccurs="0"/>
 *                     &lt;element name="searchField" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                     &lt;element name="sorts" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="sort" maxOccurs="unbounded">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;attribute name="name" use="required">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;minLength value="1"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/attribute>
 *                                       &lt;attribute name="method" use="required">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;enumeration value="asc"/>
 *                                             &lt;enumeration value="desc"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/attribute>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element ref="{}filters" minOccurs="0"/>
 *                     &lt;element ref="{}channel"/>
 *                     &lt;element name="page" minOccurs="0">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                           &lt;minInclusive value="1"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                     &lt;element ref="{}productsPerPage" minOccurs="0"/>
 *                     &lt;element ref="{}seoPath" minOccurs="0"/>
 *                     &lt;element name="customParameters" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="customParameter" maxOccurs="unbounded">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                         &lt;element name="values" minOccurs="0">
 *                                           &lt;complexType>
 *                                             &lt;complexContent>
 *                                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                 &lt;sequence>
 *                                                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                                                 &lt;/sequence>
 *                                               &lt;/restriction>
 *                                             &lt;/complexContent>
 *                                           &lt;/complexType>
 *                                         &lt;/element>
 *                                       &lt;/sequence>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element ref="{}breadCrumbTrail" minOccurs="0"/>
 *           &lt;element ref="{}singleWordSearch" minOccurs="0"/>
 *           &lt;element ref="{}campaigns" minOccurs="0"/>
 *           &lt;element ref="{}asn" minOccurs="0"/>
 *           &lt;element ref="{}paging" minOccurs="0"/>
 *           &lt;element ref="{}sorting" minOccurs="0"/>
 *           &lt;element ref="{}results" minOccurs="0"/>
 *           &lt;element name="refKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/sequence>
 *         &lt;element name="productCampaigns">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}campaigns" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;sequence>
 *           &lt;element ref="{}error"/>
 *           &lt;element ref="{}stacktrace" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "searchStatus",
    "articleNumberSearchStatus",
    "searchTimedOut",
    "productsPerPageOptions",
    "searchControlParams",
    "searchParams",
    "breadCrumbTrail",
    "singleWordSearch",
    "campaigns",
    "asn",
    "paging",
    "sorting",
    "results",
    "refKey",
    "productCampaigns",
    "error",
    "stacktrace"
})
@XmlRootElement(name = "ff")
public class Ff {

    protected String searchStatus;
    protected String articleNumberSearchStatus;
    protected Boolean searchTimedOut;
    protected Ff.ProductsPerPageOptions productsPerPageOptions;
    protected Ff.SearchControlParams searchControlParams;
    protected Ff.SearchParams searchParams;
    protected BreadCrumbTrail breadCrumbTrail;
    protected SingleWordSearch singleWordSearch;
    protected Campaigns campaigns;
    protected Asn asn;
    protected Paging paging;
    protected Sorting sorting;
    protected Results results;
    protected String refKey;
    protected Ff.ProductCampaigns productCampaigns;
    protected String error;
    protected String stacktrace;

    /**
     * Gets the value of the searchStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchStatus() {
        return searchStatus;
    }

    /**
     * Sets the value of the searchStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchStatus(String value) {
        this.searchStatus = value;
    }

    /**
     * Gets the value of the articleNumberSearchStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArticleNumberSearchStatus() {
        return articleNumberSearchStatus;
    }

    /**
     * Sets the value of the articleNumberSearchStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArticleNumberSearchStatus(String value) {
        this.articleNumberSearchStatus = value;
    }

    /**
     * Gets the value of the searchTimedOut property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSearchTimedOut() {
        return searchTimedOut;
    }

    /**
     * Sets the value of the searchTimedOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSearchTimedOut(Boolean value) {
        this.searchTimedOut = value;
    }

    /**
     * Gets the value of the productsPerPageOptions property.
     * 
     * @return
     *     possible object is
     *     {@link Ff.ProductsPerPageOptions }
     *     
     */
    public Ff.ProductsPerPageOptions getProductsPerPageOptions() {
        return productsPerPageOptions;
    }

    /**
     * Sets the value of the productsPerPageOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ff.ProductsPerPageOptions }
     *     
     */
    public void setProductsPerPageOptions(Ff.ProductsPerPageOptions value) {
        this.productsPerPageOptions = value;
    }

    /**
     * Gets the value of the searchControlParams property.
     * 
     * @return
     *     possible object is
     *     {@link Ff.SearchControlParams }
     *     
     */
    public Ff.SearchControlParams getSearchControlParams() {
        return searchControlParams;
    }

    /**
     * Sets the value of the searchControlParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ff.SearchControlParams }
     *     
     */
    public void setSearchControlParams(Ff.SearchControlParams value) {
        this.searchControlParams = value;
    }

    /**
     * Gets the value of the searchParams property.
     * 
     * @return
     *     possible object is
     *     {@link Ff.SearchParams }
     *     
     */
    public Ff.SearchParams getSearchParams() {
        return searchParams;
    }

    /**
     * Sets the value of the searchParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ff.SearchParams }
     *     
     */
    public void setSearchParams(Ff.SearchParams value) {
        this.searchParams = value;
    }

    /**
     * Gets the value of the breadCrumbTrail property.
     * 
     * @return
     *     possible object is
     *     {@link BreadCrumbTrail }
     *     
     */
    public BreadCrumbTrail getBreadCrumbTrail() {
        return breadCrumbTrail;
    }

    /**
     * Sets the value of the breadCrumbTrail property.
     * 
     * @param value
     *     allowed object is
     *     {@link BreadCrumbTrail }
     *     
     */
    public void setBreadCrumbTrail(BreadCrumbTrail value) {
        this.breadCrumbTrail = value;
    }

    /**
     * Gets the value of the singleWordSearch property.
     * 
     * @return
     *     possible object is
     *     {@link SingleWordSearch }
     *     
     */
    public SingleWordSearch getSingleWordSearch() {
        return singleWordSearch;
    }

    /**
     * Sets the value of the singleWordSearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link SingleWordSearch }
     *     
     */
    public void setSingleWordSearch(SingleWordSearch value) {
        this.singleWordSearch = value;
    }

    /**
     * Gets the value of the campaigns property.
     * 
     * @return
     *     possible object is
     *     {@link Campaigns }
     *     
     */
    public Campaigns getCampaigns() {
        return campaigns;
    }

    /**
     * Sets the value of the campaigns property.
     * 
     * @param value
     *     allowed object is
     *     {@link Campaigns }
     *     
     */
    public void setCampaigns(Campaigns value) {
        this.campaigns = value;
    }

    /**
     * Gets the value of the asn property.
     * 
     * @return
     *     possible object is
     *     {@link Asn }
     *     
     */
    public Asn getAsn() {
        return asn;
    }

    /**
     * Sets the value of the asn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Asn }
     *     
     */
    public void setAsn(Asn value) {
        this.asn = value;
    }

    /**
     * Gets the value of the paging property.
     * 
     * @return
     *     possible object is
     *     {@link Paging }
     *     
     */
    public Paging getPaging() {
        return paging;
    }

    /**
     * Sets the value of the paging property.
     * 
     * @param value
     *     allowed object is
     *     {@link Paging }
     *     
     */
    public void setPaging(Paging value) {
        this.paging = value;
    }

    /**
     * Gets the value of the sorting property.
     * 
     * @return
     *     possible object is
     *     {@link Sorting }
     *     
     */
    public Sorting getSorting() {
        return sorting;
    }

    /**
     * Sets the value of the sorting property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sorting }
     *     
     */
    public void setSorting(Sorting value) {
        this.sorting = value;
    }

    /**
     * Gets the value of the results property.
     * 
     * @return
     *     possible object is
     *     {@link Results }
     *     
     */
    public Results getResults() {
        return results;
    }

    /**
     * Sets the value of the results property.
     * 
     * @param value
     *     allowed object is
     *     {@link Results }
     *     
     */
    public void setResults(Results value) {
        this.results = value;
    }

    /**
     * Gets the value of the refKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefKey() {
        return refKey;
    }

    /**
     * Sets the value of the refKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefKey(String value) {
        this.refKey = value;
    }

    /**
     * Gets the value of the productCampaigns property.
     * 
     * @return
     *     possible object is
     *     {@link Ff.ProductCampaigns }
     *     
     */
    public Ff.ProductCampaigns getProductCampaigns() {
        return productCampaigns;
    }

    /**
     * Sets the value of the productCampaigns property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ff.ProductCampaigns }
     *     
     */
    public void setProductCampaigns(Ff.ProductCampaigns value) {
        this.productCampaigns = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setError(String value) {
        this.error = value;
    }

    /**
     * Gets the value of the stacktrace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStacktrace() {
        return stacktrace;
    }

    /**
     * Sets the value of the stacktrace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStacktrace(String value) {
        this.stacktrace = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}campaigns" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "campaigns"
    })
    public static class ProductCampaigns {

        protected Campaigns campaigns;

        /**
         * Gets the value of the campaigns property.
         * 
         * @return
         *     possible object is
         *     {@link Campaigns }
         *     
         */
        public Campaigns getCampaigns() {
            return campaigns;
        }

        /**
         * Sets the value of the campaigns property.
         * 
         * @param value
         *     allowed object is
         *     {@link Campaigns }
         *     
         */
        public void setCampaigns(Campaigns value) {
            this.campaigns = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="option" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{}searchParams"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="default" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="selected" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "option"
    })
    public static class ProductsPerPageOptions {

        protected List<Ff.ProductsPerPageOptions.Option> option;
        @XmlAttribute(name = "default", required = true)
        protected BigInteger _default;
        @XmlAttribute(name = "selected", required = true)
        protected BigInteger selected;

        /**
         * Gets the value of the option property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the option property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOption().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Ff.ProductsPerPageOptions.Option }
         * 
         * 
         */
        public List<Ff.ProductsPerPageOptions.Option> getOption() {
            if (option == null) {
                option = new ArrayList<Ff.ProductsPerPageOptions.Option>();
            }
            return this.option;
        }

        /**
         * Gets the value of the default property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getDefault() {
            return _default;
        }

        /**
         * Sets the value of the default property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setDefault(BigInteger value) {
            this._default = value;
        }

        /**
         * Gets the value of the selected property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getSelected() {
            return selected;
        }

        /**
         * Sets the value of the selected property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setSelected(BigInteger value) {
            this.selected = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{}searchParams"/>
         *       &lt;/sequence>
         *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "searchParams"
        })
        public static class Option {

            @XmlElement(required = true)
            protected String searchParams;
            @XmlAttribute(name = "value", required = true)
            protected BigInteger value;

            /**
             * Gets the value of the searchParams property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSearchParams() {
                return searchParams;
            }

            /**
             * Sets the value of the searchParams property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSearchParams(String value) {
                this.searchParams = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setValue(BigInteger value) {
                this.value = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="disableCache" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="generateAdvisorTree" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="idsOnly" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="useAsn" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="useCampaigns" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="useFoundWords" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="useKeywords" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "disableCache",
        "generateAdvisorTree",
        "idsOnly",
        "useAsn",
        "useCampaigns",
        "useFoundWords",
        "useKeywords"
    })
    public static class SearchControlParams {

        protected boolean disableCache;
        protected boolean generateAdvisorTree;
        protected boolean idsOnly;
        protected boolean useAsn;
        protected boolean useCampaigns;
        protected boolean useFoundWords;
        protected boolean useKeywords;

        /**
         * Gets the value of the disableCache property.
         * 
         */
        public boolean isDisableCache() {
            return disableCache;
        }

        /**
         * Sets the value of the disableCache property.
         * 
         */
        public void setDisableCache(boolean value) {
            this.disableCache = value;
        }

        /**
         * Gets the value of the generateAdvisorTree property.
         * 
         */
        public boolean isGenerateAdvisorTree() {
            return generateAdvisorTree;
        }

        /**
         * Sets the value of the generateAdvisorTree property.
         * 
         */
        public void setGenerateAdvisorTree(boolean value) {
            this.generateAdvisorTree = value;
        }

        /**
         * Gets the value of the idsOnly property.
         * 
         */
        public boolean isIdsOnly() {
            return idsOnly;
        }

        /**
         * Sets the value of the idsOnly property.
         * 
         */
        public void setIdsOnly(boolean value) {
            this.idsOnly = value;
        }

        /**
         * Gets the value of the useAsn property.
         * 
         */
        public boolean isUseAsn() {
            return useAsn;
        }

        /**
         * Sets the value of the useAsn property.
         * 
         */
        public void setUseAsn(boolean value) {
            this.useAsn = value;
        }

        /**
         * Gets the value of the useCampaigns property.
         * 
         */
        public boolean isUseCampaigns() {
            return useCampaigns;
        }

        /**
         * Sets the value of the useCampaigns property.
         * 
         */
        public void setUseCampaigns(boolean value) {
            this.useCampaigns = value;
        }

        /**
         * Gets the value of the useFoundWords property.
         * 
         */
        public boolean isUseFoundWords() {
            return useFoundWords;
        }

        /**
         * Sets the value of the useFoundWords property.
         * 
         */
        public void setUseFoundWords(boolean value) {
            this.useFoundWords = value;
        }

        /**
         * Gets the value of the useKeywords property.
         * 
         */
        public boolean isUseKeywords() {
            return useKeywords;
        }

        /**
         * Sets the value of the useKeywords property.
         * 
         */
        public void setUseKeywords(boolean value) {
            this.useKeywords = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}searchPhrase" minOccurs="0"/>
     *         &lt;element name="searchField" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="sorts" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="sort" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="name" use="required">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;minLength value="1"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                           &lt;attribute name="method" use="required">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;enumeration value="asc"/>
     *                                 &lt;enumeration value="desc"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element ref="{}filters" minOccurs="0"/>
     *         &lt;element ref="{}channel"/>
     *         &lt;element name="page" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *               &lt;minInclusive value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element ref="{}productsPerPage" minOccurs="0"/>
     *         &lt;element ref="{}seoPath" minOccurs="0"/>
     *         &lt;element name="customParameters" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="customParameter" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="values" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "searchPhrase",
        "searchField",
        "sorts",
        "filters",
        "channel",
        "page",
        "productsPerPage",
        "seoPath",
        "customParameters"
    })
    public static class SearchParams {

        protected String searchPhrase;
        protected String searchField;
        protected Ff.SearchParams.Sorts sorts;
        protected Filters filters;
        @XmlElement(required = true)
        protected String channel;
        protected Integer page;
        protected Integer productsPerPage;
        protected String seoPath;
        protected Ff.SearchParams.CustomParameters customParameters;

        /**
         * Gets the value of the searchPhrase property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSearchPhrase() {
            return searchPhrase;
        }

        /**
         * Sets the value of the searchPhrase property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSearchPhrase(String value) {
            this.searchPhrase = value;
        }

        /**
         * Gets the value of the searchField property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSearchField() {
            return searchField;
        }

        /**
         * Sets the value of the searchField property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSearchField(String value) {
            this.searchField = value;
        }

        /**
         * Gets the value of the sorts property.
         * 
         * @return
         *     possible object is
         *     {@link Ff.SearchParams.Sorts }
         *     
         */
        public Ff.SearchParams.Sorts getSorts() {
            return sorts;
        }

        /**
         * Sets the value of the sorts property.
         * 
         * @param value
         *     allowed object is
         *     {@link Ff.SearchParams.Sorts }
         *     
         */
        public void setSorts(Ff.SearchParams.Sorts value) {
            this.sorts = value;
        }

        /**
         * Gets the value of the filters property.
         * 
         * @return
         *     possible object is
         *     {@link Filters }
         *     
         */
        public Filters getFilters() {
            return filters;
        }

        /**
         * Sets the value of the filters property.
         * 
         * @param value
         *     allowed object is
         *     {@link Filters }
         *     
         */
        public void setFilters(Filters value) {
            this.filters = value;
        }

        /**
         * Gets the value of the channel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChannel() {
            return channel;
        }

        /**
         * Sets the value of the channel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChannel(String value) {
            this.channel = value;
        }

        /**
         * Gets the value of the page property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getPage() {
            return page;
        }

        /**
         * Sets the value of the page property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPage(Integer value) {
            this.page = value;
        }

        /**
         * Gets the value of the productsPerPage property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getProductsPerPage() {
            return productsPerPage;
        }

        /**
         * Sets the value of the productsPerPage property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setProductsPerPage(Integer value) {
            this.productsPerPage = value;
        }

        /**
         * Gets the value of the seoPath property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSeoPath() {
            return seoPath;
        }

        /**
         * Sets the value of the seoPath property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSeoPath(String value) {
            this.seoPath = value;
        }

        /**
         * Gets the value of the customParameters property.
         * 
         * @return
         *     possible object is
         *     {@link Ff.SearchParams.CustomParameters }
         *     
         */
        public Ff.SearchParams.CustomParameters getCustomParameters() {
            return customParameters;
        }

        /**
         * Sets the value of the customParameters property.
         * 
         * @param value
         *     allowed object is
         *     {@link Ff.SearchParams.CustomParameters }
         *     
         */
        public void setCustomParameters(Ff.SearchParams.CustomParameters value) {
            this.customParameters = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="customParameter" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="values" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "customParameter"
        })
        public static class CustomParameters {

            @XmlElement(required = true)
            protected List<Ff.SearchParams.CustomParameters.CustomParameter> customParameter;

            /**
             * Gets the value of the customParameter property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the customParameter property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCustomParameter().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Ff.SearchParams.CustomParameters.CustomParameter }
             * 
             * 
             */
            public List<Ff.SearchParams.CustomParameters.CustomParameter> getCustomParameter() {
                if (customParameter == null) {
                    customParameter = new ArrayList<Ff.SearchParams.CustomParameters.CustomParameter>();
                }
                return this.customParameter;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="values" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "name",
                "values"
            })
            public static class CustomParameter {

                protected String name;
                protected Ff.SearchParams.CustomParameters.CustomParameter.Values values;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the values property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Ff.SearchParams.CustomParameters.CustomParameter.Values }
                 *     
                 */
                public Ff.SearchParams.CustomParameters.CustomParameter.Values getValues() {
                    return values;
                }

                /**
                 * Sets the value of the values property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Ff.SearchParams.CustomParameters.CustomParameter.Values }
                 *     
                 */
                public void setValues(Ff.SearchParams.CustomParameters.CustomParameter.Values value) {
                    this.values = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class Values {

                    protected List<String> value;

                    /**
                     * Gets the value of the value property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the value property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getValue().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link String }
                     * 
                     * 
                     */
                    public List<String> getValue() {
                        if (value == null) {
                            value = new ArrayList<String>();
                        }
                        return this.value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="sort" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="name" use="required">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;minLength value="1"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *                 &lt;attribute name="method" use="required">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;enumeration value="asc"/>
         *                       &lt;enumeration value="desc"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "sort"
        })
        public static class Sorts {

            @XmlElement(required = true)
            protected List<Ff.SearchParams.Sorts.Sort> sort;

            /**
             * Gets the value of the sort property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the sort property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSort().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Ff.SearchParams.Sorts.Sort }
             * 
             * 
             */
            public List<Ff.SearchParams.Sorts.Sort> getSort() {
                if (sort == null) {
                    sort = new ArrayList<Ff.SearchParams.Sorts.Sort>();
                }
                return this.sort;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="name" use="required">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;minLength value="1"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *       &lt;attribute name="method" use="required">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;enumeration value="asc"/>
             *             &lt;enumeration value="desc"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Sort {

                @XmlAttribute(name = "name", required = true)
                protected String name;
                @XmlAttribute(name = "method", required = true)
                protected String method;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the method property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMethod() {
                    return method;
                }

                /**
                 * Sets the value of the method property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMethod(String value) {
                    this.method = value;
                }

            }

        }

    }

}
