//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.11 at 01:24:08 PM CEST 
//


package de.factfinder.xml610.search;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}searchParams"/>
 *         &lt;element name="settings">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="linkCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="nextCaption" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="previousCaption" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="pageCount" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="currentPage" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="productsPerPage">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "searchParams",
    "settings"
})
@XmlRootElement(name = "paging")
public class Paging {

    @XmlElement(required = true)
    protected String searchParams;
    @XmlElement(required = true)
    protected Paging.Settings settings;
    @XmlAttribute(name = "pageCount", required = true)
    protected int pageCount;
    @XmlAttribute(name = "currentPage", required = true)
    protected int currentPage;
    @XmlAttribute(name = "productsPerPage")
    protected Integer productsPerPage;

    /**
     * Gets the value of the searchParams property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchParams() {
        return searchParams;
    }

    /**
     * Sets the value of the searchParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchParams(String value) {
        this.searchParams = value;
    }

    /**
     * Gets the value of the settings property.
     * 
     * @return
     *     possible object is
     *     {@link Paging.Settings }
     *     
     */
    public Paging.Settings getSettings() {
        return settings;
    }

    /**
     * Sets the value of the settings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Paging.Settings }
     *     
     */
    public void setSettings(Paging.Settings value) {
        this.settings = value;
    }

    /**
     * Gets the value of the pageCount property.
     * 
     */
    public int getPageCount() {
        return pageCount;
    }

    /**
     * Sets the value of the pageCount property.
     * 
     */
    public void setPageCount(int value) {
        this.pageCount = value;
    }

    /**
     * Gets the value of the currentPage property.
     * 
     */
    public int getCurrentPage() {
        return currentPage;
    }

    /**
     * Sets the value of the currentPage property.
     * 
     */
    public void setCurrentPage(int value) {
        this.currentPage = value;
    }

    /**
     * Gets the value of the productsPerPage property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProductsPerPage() {
        return productsPerPage;
    }

    /**
     * Sets the value of the productsPerPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProductsPerPage(Integer value) {
        this.productsPerPage = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="linkCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="nextCaption" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="previousCaption" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "linkCount",
        "nextCaption",
        "previousCaption"
    })
    public static class Settings {

        protected int linkCount;
        @XmlElement(required = true)
        protected String nextCaption;
        @XmlElement(required = true)
        protected String previousCaption;

        /**
         * Gets the value of the linkCount property.
         * 
         */
        public int getLinkCount() {
            return linkCount;
        }

        /**
         * Sets the value of the linkCount property.
         * 
         */
        public void setLinkCount(int value) {
            this.linkCount = value;
        }

        /**
         * Gets the value of the nextCaption property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNextCaption() {
            return nextCaption;
        }

        /**
         * Sets the value of the nextCaption property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNextCaption(String value) {
            this.nextCaption = value;
        }

        /**
         * Gets the value of the previousCaption property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPreviousCaption() {
            return previousCaption;
        }

        /**
         * Sets the value of the previousCaption property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPreviousCaption(String value) {
            this.previousCaption = value;
        }

    }

}
