//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.11 at 01:24:08 PM CEST 
//


package de.factfinder.xml610.search;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}similarWords"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "similarWords"
})
@XmlRootElement(name = "recommendation")
public class Recommendation {

    @XmlElement(required = true)
    protected SimilarWords similarWords;

    /**
     * Gets the value of the similarWords property.
     * 
     * @return
     *     possible object is
     *     {@link SimilarWords }
     *     
     */
    public SimilarWords getSimilarWords() {
        return similarWords;
    }

    /**
     * Sets the value of the similarWords property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimilarWords }
     *     
     */
    public void setSimilarWords(SimilarWords value) {
        this.similarWords = value;
    }

}
