//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.11 at 01:24:14 PM CEST 
//


package de.factfinder.xml610.similarrecords;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}similarAttributes"/>
 *         &lt;element ref="{}similarRecords"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "similarAttributes",
    "similarRecords"
})
@XmlRootElement(name = "ff")
public class Ff {

    @XmlElement(required = true)
    protected SimilarAttributes similarAttributes;
    @XmlElement(required = true)
    protected SimilarRecords similarRecords;

    /**
     * Gets the value of the similarAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link SimilarAttributes }
     *     
     */
    public SimilarAttributes getSimilarAttributes() {
        return similarAttributes;
    }

    /**
     * Sets the value of the similarAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimilarAttributes }
     *     
     */
    public void setSimilarAttributes(SimilarAttributes value) {
        this.similarAttributes = value;
    }

    /**
     * Gets the value of the similarRecords property.
     * 
     * @return
     *     possible object is
     *     {@link SimilarRecords }
     *     
     */
    public SimilarRecords getSimilarRecords() {
        return similarRecords;
    }

    /**
     * Sets the value of the similarRecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimilarRecords }
     *     
     */
    public void setSimilarRecords(SimilarRecords value) {
        this.similarRecords = value;
    }

}
